In [1]:
import copy 
import os
import pandas as pd
import random
random.seed(42)
# Directory containing neocoder output files
data_dir = "../data/raw/neocoder"

In [12]:
# List all CSV files in the directory
# files = [f for f in os.listdir(data_dir) if f.endswith('.csv')]

# files
model_lst = [
    'Qwen2.5-7B-Instruct',
    'gpt-4.1',
    'OLMo-2-1124-13B-Instruct'
]
files = [mo + '_creativity.csv' for mo in model_lst]

rows_per_model = 20
min_rows = min([pd.read_csv(os.path.join(data_dir, file)).shape[0] for file in files])

dfs = []
for file in files:
    file_path = os.path.join(data_dir, file)
    df = pd.read_csv(file_path).dropna(subset=['machine_solutions'])
    # Add a column for model name (derived from file name, without extension)
    model_name = os.path.splitext(file)[0]
    df['model'] = model_name
    random.seed(42)
    randomly_sampled_rows = random.sample(range(min(min_rows, df.shape[0])), rows_per_model)
    df = copy.deepcopy(df.iloc[randomly_sampled_rows])
    dfs.append(df)

# Concatenate all dataframes into one big table
big_table = pd.concat(dfs, ignore_index=True)

In [14]:
# randomly_sampled_rows

In [ ]:
# human_annotation/data/mturk_input/neocoder/neocoder_sampled_1.csv 
# human_annotation/data/mturk_input/neocoder/neocoder_sampled_2.csv 
# human_annotation/data/mturk_input/neocoder/neocoder_sampled_3.csv

In [21]:
# sample_df

In [15]:
big_table.model.unique()

array(['Qwen2.5-7B-Instruct_creativity', 'gpt-4.1_creativity',
       'OLMo-2-1124-13B-Instruct_creativity'], dtype=object)

In [16]:
big_table.shape

(60, 11)

In [17]:
big_table.head()

,problem_id,dp,constraints,machine_techniques,human_techniques,machine_solutions,correctness,follow_constraints,new_techniques,new_techniques_ratio,model
0,1746A,1,['for loop'],"['if statement', 'while loop', 'for loop']","['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...",def solve():\n import sys\n input = sys....,False,False,3,1.0,Qwen2.5-7B-Instruct_creativity
1,1867A,0,['this is the og problem'],"['for loop', 'set', 'if statement']","['t', ' ', '=', 'i', 'n', '(', 'p', 'u', ')', ...","def solve():\n from sys import stdin, stdou...",False,True,3,1.0,Qwen2.5-7B-Instruct_creativity
2,1894A,1,['for loop'],['misc'],"['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...",def solve():\n from itertools import accumu...,False,True,1,1.0,Qwen2.5-7B-Instruct_creativity
3,1729A,4,"['misc', 'for loop', 'tuple', 'if statement']","['if statement', 'for loop']","['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...",def solve():\n import sys\n \n input ...,False,False,2,1.0,Qwen2.5-7B-Instruct_creativity
4,1832A,5,"['if statement', 'hashmap', 'for loop', 'set',...","['if statement', 'for loop', 'dictionary', 're...","['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...",def solve():\n from sys import stdin\n \...,False,False,5,1.0,Qwen2.5-7B-Instruct_creativity

In [22]:
big_table = pd.read_csv("../data/mturk_input/neocoder_sampled_all.csv")

In [23]:
start = 0
end = big_table.shape[0]
step = 20

while start < end:
    batch_df = big_table.iloc[start:start+step]
    batch_number = (start // step) + 1
    batch_df.to_csv(f'../data/mturk_input/neocoder_sampled_{batch_number}.csv', index=False)
    print(f"Saved batch {batch_number} with {batch_df.shape[0]} rows.")
    start += step
# big_table.head(15).drop(columns=['eval_cot_input', 'eval_cot_pred']).to_csv('../data/mturk_input/ttct_sampled_1.csv', index=False)

Saved batch 1 with 20 rows.
Saved batch 2 with 20 rows.
Saved batch 3 with 20 rows.

In [57]:
print(big_table['machine_solutions'].values[45])

def solve():
    n, cnt = map(int, input().split())
    balls = [0] * (n + 1)
    for i in range(n):
        cnt_i = int(input())
        balls[cnt_i] += cnt_i
    parity = balls[-1] % 2

    def can_stay(x):
        return balls[x] >= 2

    def find_color(start):
        if can_stay(start):
            return start
        for i in range(n):
            if balls[i] >= 2 and can_stay(i) and balls[start] - 1 < balls[i]:
                return find_color(i)
        return start

    return find_color(1) if parity == 1 else find_color(2)

In [43]:
big_table['machine_solutions'].values[45]

'def solve():\n    pass\n'

In [45]:
batch_df

,problem_id,dp,constraints,machine_techniques,human_techniques,machine_solutions,correctness,follow_constraints,new_techniques,new_techniques_ratio,model
40,1849A,2,"['if statement', 'tuple']",['if statement'],"['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...","def solve(b, c, h):\n layers = min(b, c + h...",False,False,1,1.0,OLMo-2-1124-13B-Instruct_creativity
41,1886A,2,"['if statement', 'for loop']","['for loop', 'if statement', 'tuple']","['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...",def solve(n):\n def find_triplet(start):\n ...,False,False,3,1.0,OLMo-2-1124-13B-Instruct_creativity
42,1788A,0,['this is the og problem'],[],"['#', 'i', 'n', 'c', 'l', 'u', 'd', 'e', ' ', ...",NaN,False,True,0,0.0,OLMo-2-1124-13B-Instruct_creativity
43,1796A,1,['for loop'],[],"['K', ' ', '=', 'i', 'n', 't', '(', 'p', 'u', ...",NaN,False,True,0,0.0,OLMo-2-1124-13B-Instruct_creativity
44,1805B,2,"['for loop', 'if statement']",['pass statement'],"['t', '=', 'i', 'n', '(', 'p', 'u', ')', '\r',...",def solve():\n pass\n,False,True,1,1.0,OLMo-2-1124-13B-Instruct_creativity
45,1840A,0,['this is the og problem'],['pass statement'],"['t', ' ', '=', 'i', 'n', '(', 'p', 'u', ')', ...",def solve():\n pass\n,False,True,1,1.0,OLMo-2-1124-13B-Instruct_creativity
46,1851A,3,"['if statement', 'dictionary', 'tuple']",[],"['t', ' ', '=', 'i', 'n', '(', 'p', 'u', ')', ...",NaN,False,True,0,0.0,OLMo-2-1124-13B-Instruct_creativity
47,1857A,1,['for loop'],"['tuple', 'if statement', 'for loop', 'recursi...","['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...","def solve():\n n, *a = map(int, input().spl...",False,False,4,1.0,OLMo-2-1124-13B-Instruct_creativity
48,1731A,0,['this is the og problem'],"['dynamic programming', 'for loop']","['t', '=', 'i', 'n', '(', 'p', 'u', ')', '\r',...",def solve(arr):\n n = len(arr)\n dp = [0...,False,True,2,1.0,OLMo-2-1124-13B-Instruct_creativity
49,1883A,4,"['if statement', 'for loop', 'dictionary', 'wh...",['pass statement'],"['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...",def solve(pin_code):\n # Your Python code h...,False,True,1,1.0,OLMo-2-1124-13B-Instruct_creativity
50,1883A,0,['this is the og problem'],['pass statement'],"['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...",def solve(pin_code):\n # Write your code he...,False,True,1,1.0,OLMo-2-1124-13B-Instruct_creativity
51,1855A,3,"['hashmap', 'for loop', 'if statement']",['set'],"['t', ' ', '=', 'i', 'n', '(', 'p', 'u', ')', ...","def solve(n, p):\n import sympy as sp\n ...",False,True,1,1.0,OLMo-2-1124-13B-Instruct_creativity
52,1807A,2,"['for loop', 'tuple']",[],"['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...",NaN,False,True,0,0.0,OLMo-2-1124-13B-Instruct_creativity
53,1800A,0,['this is the og problem'],[],"['i', 'm', 'p', 'o', 'r', 't', ' ', 'e', '\r',...",NaN,False,True,0,0.0,OLMo-2-1124-13B-Instruct_creativity
54,1702B,1,['if statement'],['misc'],"['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...",deforces\nin\n4\ndays.\nFor the fifth test cas...,False,True,1,1.0,OLMo-2-1124-13B-Instruct_creativity
55,1886A,5,"['if statement', 'for loop', 'tuple', 'depth f...","['recursion', 'if statement', 'while loop']","['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...",def can_form_sum(n):\n def helper(k):\n ...,False,False,3,1.0,OLMo-2-1124-13B-Instruct_creativity
56,1814A,0,['this is the og problem'],[],"['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...",NaN,False,True,0,0.0,OLMo-2-1124-13B-Instruct_creativity
57,1733A,1,['misc'],['pass statement'],"['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...","def solve(n, k, a):\n # Your implementation...",False,True,1,1.0,OLMo-2-1124-13B-Instruct_creativity
58,1806A,1,['matrix operation'],[],"['f', 'o', 'r', ' ', 'i', 'n', 'a', 'g', 'e', ...",NaN,False,True,0,0.0,OLMo-2-1124-13B-Instruct_creativity
59,1721A,3,"['if statement', 'tuple', 'for loop']",['pass statement'],"['f', 'o', 'r', ' ', '_', 'i', 'n', 'a', 'g', ...","def solve():\n def recolor_image(image1, im...",False,True,1,1.0,OLMo-2-1124-13B-Instruct_creativity

In [24]:
technique_lst = ["if statement", "for loop", "while loop", "break statement", "continue statement", "pass statement", "match statement",
"stack", "queue", "tuple", "set", "dictionary", "linked list", "tree", "graph", "heap", "hashmap", 
"two pointers", "sliding window", "matrix operation", 
"depth first search", "width first search", "back tracking", "divide & conquer", "Kadanes algorithm", "binary search", 
"recursion", "dynamic programming", "greedy algorithm", "misc", "minimax", "topological sort", "sorting", "graph traversal"]

mturk_template = ''' 
<input type="checkbox" id="{id}" name="technique" value="{id}" required="false">
<label for="{id}">{value}</label> 
'''

mturk_str = ''
for tech in technique_lst:
    # big_table[tech] = big_table['techniques'].apply(lambda x: 1 if tech in x else 0)
    id_str = tech.replace(" ", "_")
    value_str = tech
    # mturk_template.format(id=id_str, value=value_str)
    mturk_str += '\t' + mturk_template.format(id=id_str, value=value_str)

In [26]:
# print(mturk_str)