In [12]:
import pandas as pd
input_data = pd.read_csv('/ihome/xli/joh227/developer/creativityprism_git_workspace/tasks/ttct/data/outputs/temp_1/gpt-4.1-2025-04-14.csv')

In [13]:
input_data.shape

(700, 7)

In [14]:
input_data.iloc[[i * 100 for i in range(7)]]

,infer_basic_input,infer_instructive_input,infer_cot_input,infer_basic_pred,infer_instructive_pred,infer_cot_pred,question_type
0,"Common Problems Task. In this task, you will b...","Common Problems Task. In this task, you will b...","Common Problems Task. In this task, you will b...",Certainly! Here are potential problems or issu...,Sure! Here is a list of potential problems or ...,Certainly! Let’s break down the scenario step ...,5_common_problems
100,What might be the consequences if humans sudde...,The Consequences Task. Your task is to imagine...,What might be the consequences if humans sudde...,If humans suddenly lost the ability to sleep *...,Certainly! Here is a comprehensive list of pos...,"Absolutely, let’s break down the possible cons...",2_consequences
200,Creativity Improvement Task. You'll be present...,Creativity Improvement Task. The purpose of th...,Creativity Improvement Task. You'll be present...,Certainly! Here are a variety of ways to impro...,Absolutely! Here are a wide variety of creativ...,Great! Let’s break it down step by step. The h...,6_improvement
300,You are to construct a narrative or story base...,"Imaginative Stories Task. In this task, your c...",You are to construct a narrative or story base...,"It was an old mystery, one that had burrowed i...",**The Dog That Did Not Bark**\n\nOn the far ed...,Certainly! Let’s build a story in steps:\n\n**...,7_story
400,Just suppose you woke up one morning and found...,Just Suppose Task. The purpose of this task is...,Just suppose you woke up one morning and found...,Absolutely! If I woke up one morning and disco...,1. Soar above my neighborhood to get a bird’s-...,"Absolutely, let's imagine this step by step!\n...",3_just_suppose
500,"If all cars were to suddenly stop working, how...",Creativity Situation Task. The purpose of this...,"If all cars were to suddenly stop working, how...","If all cars suddenly stopped working, you'd st...",Absolutely! Here’s a creative brainstorm for w...,Sure! Let's think step by step about how to tr...,4_situation
600,Unusual Uses Task. You will be presented with ...,Unusual Uses Task. The purpose of this task is...,Unusual Uses Task. You will be presented with ...,Absolutely! Here are some unusual and innovati...,"Of course! Here are some unusual, innovative, ...","Absolutely! Here are unusual, innovative, or n...",1_unusual_uses

In [15]:
# '1_unusual_uses', '5_common_problems', '4_situation', '6_improvement', '2_consequences', '3_just_suppose', '7_story'

In [16]:
problem_types = {
    0: "5_common_problems",
    1: "2_consequences",
    2: "6_improvement",
    3: "7_story",
    4: "3_just_suppose",
    5: "4_situation",
    6: "1_unusual_uses"
}

In [17]:
all_question_types = []
for i in range(7):
    all_question_types += [problem_types[i]] * 100
input_data['question_type'] = all_question_types

In [18]:
input_data.iloc[[i * 100 for i in range(7)]]

,infer_basic_input,infer_instructive_input,infer_cot_input,infer_basic_pred,infer_instructive_pred,infer_cot_pred,question_type
0,"Common Problems Task. In this task, you will b...","Common Problems Task. In this task, you will b...","Common Problems Task. In this task, you will b...",Certainly! Here are potential problems or issu...,Sure! Here is a list of potential problems or ...,Certainly! Let’s break down the scenario step ...,5_common_problems
100,What might be the consequences if humans sudde...,The Consequences Task. Your task is to imagine...,What might be the consequences if humans sudde...,If humans suddenly lost the ability to sleep *...,Certainly! Here is a comprehensive list of pos...,"Absolutely, let’s break down the possible cons...",2_consequences
200,Creativity Improvement Task. You'll be present...,Creativity Improvement Task. The purpose of th...,Creativity Improvement Task. You'll be present...,Certainly! Here are a variety of ways to impro...,Absolutely! Here are a wide variety of creativ...,Great! Let’s break it down step by step. The h...,6_improvement
300,You are to construct a narrative or story base...,"Imaginative Stories Task. In this task, your c...",You are to construct a narrative or story base...,"It was an old mystery, one that had burrowed i...",**The Dog That Did Not Bark**\n\nOn the far ed...,Certainly! Let’s build a story in steps:\n\n**...,7_story
400,Just suppose you woke up one morning and found...,Just Suppose Task. The purpose of this task is...,Just suppose you woke up one morning and found...,Absolutely! If I woke up one morning and disco...,1. Soar above my neighborhood to get a bird’s-...,"Absolutely, let's imagine this step by step!\n...",3_just_suppose
500,"If all cars were to suddenly stop working, how...",Creativity Situation Task. The purpose of this...,"If all cars were to suddenly stop working, how...","If all cars suddenly stopped working, you'd st...",Absolutely! Here’s a creative brainstorm for w...,Sure! Let's think step by step about how to tr...,4_situation
600,Unusual Uses Task. You will be presented with ...,Unusual Uses Task. The purpose of this task is...,Unusual Uses Task. You will be presented with ...,Absolutely! Here are some unusual and innovati...,"Of course! Here are some unusual, innovative, ...","Absolutely! Here are unusual, innovative, or n...",1_unusual_uses

In [19]:
input_data.to_csv('/ihome/xli/joh227/developer/creativityprism_git_workspace/tasks/ttct/data/outputs/temp_1/gpt-4.1-2025-04-14.csv', index=False)

In [29]:
# load json file
import json
import numpy as np
import pandas as pd 
from tqdm import tqdm 

def load_json_file(file_path):
    with open(file_path, 'r') as f:
        json_data = json.load(f)
    # print('Total number of items in the json file:', len(json_data))
    return json_data

In [21]:
basefile_df = pd.read_csv('../data/processed/basefile.csv')
json_data = load_json_file('../data/processed/ttct.json')

len(json_data), basefile_df.shape

(700, (700, 7))

In [30]:
def edit_distance(str1, str2):
    m = len(str1)
    n = len(str2)
    
    dp = np.zeros((m + 1, n + 1), dtype=int)

    for i in range(m + 1):
        for j in range(n + 1):
            if i == 0:
                dp[i][j] = j
            elif j == 0:
                dp[i][j] = i
            elif str1[i - 1] == str2[j - 1]:
                dp[i][j] = dp[i - 1][j - 1]
            else:
                dp[i][j] = 1 + min(dp[i - 1][j],    # Deletion
                                   dp[i][j - 1],    # Insertion
                                   dp[i - 1][j - 1]) # Substitution
    return dp[m][n]
# edit_distance(json_data)

In [32]:
# # np.unique([item['meta_data']['id'][2:] for item in json_data])
# distances = []
# for i in tqdm(range(len(json_data))):
#     distances.append(edit_distance(json_data[i]['input']['text_cot'], basefile_df['infer_cot_input'].values[i]))

# np.max(distances), np.min(distances), np.mean(distances)

In [33]:
basefile_df.head(2)

,infer_basic_input,infer_instructive_input,infer_cot_input,infer_basic_pred,infer_instructive_pred,infer_cot_pred,question_type
0,"Common Problems Task. In this task, you will b...","Common Problems Task. In this task, you will b...","Common Problems Task. In this task, you will b...",Certainly! Here are potential problems or issu...,Sure! Here is a list of potential problems or ...,Certainly! Let’s break down the scenario step ...,5_common_problems
1,"Common Problems Task. In this task, you will b...","Common Problems Task. In this task, you will b...","Common Problems Task. In this task, you will b...",**Scenario:** Organizing a cross-country road ...,Certainly! Here's a comprehensive list of pote...,Absolutely! Let’s break down the scenario: **O...,5_common_problems

In [34]:
basefile_df['infer_cot_input'].nunique()

697

In [35]:
question_type_dict = dict(zip(
    basefile_df['infer_cot_input'].values,
    basefile_df['question_type'].values
))

In [36]:
json_data[0]

{'meta_data': {'dataset': 'ttct', 'id': '1_common_problem', 'eval_func': None},
 'input': {'text_basic': 'Common Problems Task. In this task, you will be presented with a scenario or situation. Your job is to think about it and identify as many potential problems or issues that may arise in connection with each situation. The scenario is: Planning a birthday party for a 5-year-old.',
  'text_instructive': "Common Problems Task. In this task, you will be presented with a scenario or situation. Your job is to think about it and identify as many potential problems or issues that may arise in connection with the situation. There's no right or wrong answers, we're interested in how many different problems you can identify and the variety of issues you consider. Try to think outside the box and consider as many potential problems as possible. The scenario is: Planning a birthday party for a 5-year-old.",
  'text_cot': "Common Problems Task. In this task, you will be presented with a scenario or situation. Your job is to think about it and identify as many potential problems or issues that may arise in connection with each situation. Let's think step by step. The scenario is: Planning a birthday party for a 5-year-old.",
  'file': None,
  'others': {'constraints': None,
   'instructions': {'system': 'Do the following task or answer the following question.',
    'user': 'Instruction: {question}'},
   'references': {'solutions': None}}},
 'output': {'text_basic': None, 'text_instructive': None, 'text_cot': None}}

In [37]:
for item in json_data:
    item_input = item['input']['text_cot']
    item['meta_data']['question_type'] = question_type_dict[item_input]

In [38]:
def write_json_file(file_path, json_data):
    with open(file_path, 'w') as f:
        json.dump(json_data, f, indent=4)
    print(f'JSON data has been written to {file_path}') 
write_json_file('../data/processed/ttct.json', json_data)

JSON data has been written to ../data/processed/ttct.json